version: "3.9"

services:
  traefik:
    image: traefik:latest
    networks:
      traefik:
        aliases:
          - traefik
    command:
      - "--log.level=INFO"

      - "--api.dashboard=true"
      - "--api.insecure=true"

      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik"

      - "--entrypoints.web.address=:80"
      #^ - "--entrypoints.websecure.address=:443"
      #^ - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      #^ - "--entrypoints.web.http.redirections.entryPoint.scheme=https"

      #^ - "--certificatesresolvers.letsencryptresolver.acme.httpchallenge=true"
      #^ - "--certificatesresolvers.letsencryptresolver.acme.httpchallenge.entrypoint=web"
      #^ - "--certificatesresolvers.letsencryptresolver.acme.email=${ACME_EMAIL}"
      #^ - "--certificatesresolvers.letsencryptresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      # The HTTP port
      - "80:80"
      # The HTTPS port
      #^ - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./access.log:/access.log
      #^ - letsencrypt-data:/letsencrypt
    environment:
      - TZ=Europe/London
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`traefik.${DOMAIN}`)
      #^ - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.router.api.entrypoints=web
      - traefik.http.routers.api.service=api@internal
      #^ - traefik.http.routers.api.tls.certresolver=letsencryptresolver
      - traefik.port=8080

#  supa-manager:
#      build: .
#      container_name: "supa_manager"
#      networks:
#        traefik:
#          aliases:
#            - supa-manager
#      labels:
#        - "traefik.enable=true"
#        - "traefik.http.routers.supa-manager.rule=Host(`supabase.${DOMAIN}`)"
#        - "traefik.http.routers.supa-manager.entrypoints=web"
#        #^ - "traefik.http.routers.supa-manager.entrypoints=websecure"
#        #^ - "traefik.http.routers.supa-manager.tls.certresolver=letsencryptresolver"

  # TODO add database here

networks:
  traefik:
    name: traefik