// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package main

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Version struct {
	ID        pgtype.UUID
	ServiceID string
	Image     string
	Tag       string
	CreatedAt pgtype.Timestamp
	CreatedBy string
}
