// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: accounts.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :exec
INSERT INTO public.accounts (email, password_hash, username)
VALUES ($1, $2, $3)
`

type CreateAccountParams struct {
	Email        string
	PasswordHash string
	Username     string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.Exec(ctx, createAccount, arg.Email, arg.PasswordHash, arg.Username)
	return err
}

const setAccountName = `-- name: SetAccountName :exec
UPDATE public.accounts
SET first_name = $2,
    last_name  = $3
WHERE id = $1
`

type SetAccountNameParams struct {
	ID        pgtype.UUID
	FirstName pgtype.Text
	LastName  pgtype.Text
}

func (q *Queries) SetAccountName(ctx context.Context, arg SetAccountNameParams) error {
	_, err := q.db.Exec(ctx, setAccountName, arg.ID, arg.FirstName, arg.LastName)
	return err
}
