// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID           int32
	GotrueID     string
	Email        string
	PasswordHash string
	Username     string
	FirstName    pgtype.Text
	LastName     pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Migration struct {
	ID        string
	Note      pgtype.Text
	AppliedAt pgtype.Timestamptz
}

type Organization struct {
	ID           int32
	Slug         string
	Name         string
	Kind         string
	BillingEmail string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type OrganizationMembership struct {
	OrganizationID int32
	AccountID      int32
	Role           string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Project struct {
	ID             int32
	ProjectRef     string
	ProjectName    string
	OrganizationID int32
	Status         string
	CloudProvider  string
	Region         string
	JwtSecret      string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
