// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	Username     string
	FirstName    pgtype.Text
	LastName     pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Migration struct {
	ID        string
	Note      pgtype.Text
	AppliedAt pgtype.Timestamptz
}

type Organization struct {
	Slug         string
	Name         string
	Kind         string
	BillingEmail string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type OrganizationMembership struct {
	OrganizationSlug string
	AccountID        pgtype.UUID
	Role             string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type Project struct {
	ProjectRef       string
	ProjectName      string
	OrganizationSlug string
	Status           string
	CloudProvider    string
	Region           string
	JwtSecret        string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}
