// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: organizations.sql

package database

import (
	"context"
)

const getOrganizationById = `-- name: GetOrganizationById :one
SELECT slug, name, kind, billing_email, created_at, updated_at FROM public.organizations WHERE slug = $1
`

func (q *Queries) GetOrganizationById(ctx context.Context, id string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationById, id)
	var i Organization
	err := row.Scan(
		&i.Slug,
		&i.Name,
		&i.Kind,
		&i.BillingEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
