// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: organization_membership.sql

package database

import (
	"context"
)

const createOrganizationMembership = `-- name: CreateOrganizationMembership :one
INSERT INTO organization_membership (organization_id, account_id, role)
VALUES ($1, $2, $3)
RETURNING organization_id, account_id, role, created_at, updated_at
`

type CreateOrganizationMembershipParams struct {
	OrganizationID int32
	AccountID      int32
	Role           string
}

func (q *Queries) CreateOrganizationMembership(ctx context.Context, arg CreateOrganizationMembershipParams) (OrganizationMembership, error) {
	row := q.db.QueryRow(ctx, createOrganizationMembership, arg.OrganizationID, arg.AccountID, arg.Role)
	var i OrganizationMembership
	err := row.Scan(
		&i.OrganizationID,
		&i.AccountID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
