{{- if .Values.global.registry.deploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: registry:2
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: registry-data
          mountPath: /var/lib/registry
      volumes:
      - name: registry-data
        {{- if .Values.global.registry.persistence.enabled }}
        persistentVolumeClaim:
          claimName: registry-pvc
        {{- else }}
        emptyDir: {}
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: registry
  ports:
  - port: 5000
    targetPort: 5000
{{- end }} 