{{- if .Values.studio.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: studio
  namespace: {{ .Values.global.namespace }}
  {{- with .Values.studio.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.studio.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.studio.ingress.host }}
      secretName: studio-tls
  {{- end }}
  rules:
    - host: {{ .Values.studio.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: studio
                port:
                  number: {{ .Values.studio.service.port }}
{{- end }} 