apiVersion: apps/v1
kind: Deployment
metadata:
  name: supa-manager
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supa-manager
  template:
    metadata:
      labels:
        app: supa-manager
    spec:
      containers:
      - name: supa-manager
        image: "{{ .Values.global.imageRegistry }}/{{ .Values.supaManager.image.repository }}:{{ .Values.supaManager.image.tag }}"
        imagePullPolicy: {{ .Values.supaManager.image.pullPolicy }}
        resources:
          {{- toYaml .Values.supaManager.resources | nindent 12 }}
        envFrom:
        - configMapRef:
            name: supa-manager-config 